// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct AddOptions : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static AddOptions GetRootAsAddOptions(ByteBuffer _bb) { return GetRootAsAddOptions(_bb, new AddOptions()); }
  public static AddOptions GetRootAsAddOptions(ByteBuffer _bb, AddOptions obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AddOptions __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public tflite.ActivationFunctionType FusedActivationFunction { get { int o = __p.__offset(4); return o != 0 ? (tflite.ActivationFunctionType)__p.bb.GetSbyte(o + __p.bb_pos) : tflite.ActivationFunctionType.NONE; } }
  public bool PotScaleInt16 { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)true; } }

  public static Offset<tflite.AddOptions> CreateAddOptions(FlatBufferBuilder builder,
      tflite.ActivationFunctionType fused_activation_function = tflite.ActivationFunctionType.NONE,
      bool pot_scale_int16 = true) {
    builder.StartTable(2);
    AddOptions.AddPotScaleInt16(builder, pot_scale_int16);
    AddOptions.AddFusedActivationFunction(builder, fused_activation_function);
    return AddOptions.EndAddOptions(builder);
  }

  public static void StartAddOptions(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddFusedActivationFunction(FlatBufferBuilder builder, tflite.ActivationFunctionType fusedActivationFunction) { builder.AddSbyte(0, (sbyte)fusedActivationFunction, 0); }
  public static void AddPotScaleInt16(FlatBufferBuilder builder, bool potScaleInt16) { builder.AddBool(1, potScaleInt16, true); }
  public static Offset<tflite.AddOptions> EndAddOptions(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<tflite.AddOptions>(o);
  }
};


}
