// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ArgMinOptions : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static ArgMinOptions GetRootAsArgMinOptions(ByteBuffer _bb) { return GetRootAsArgMinOptions(_bb, new ArgMinOptions()); }
  public static ArgMinOptions GetRootAsArgMinOptions(ByteBuffer _bb, ArgMinOptions obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ArgMinOptions __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public tflite.TensorType OutputType { get { int o = __p.__offset(4); return o != 0 ? (tflite.TensorType)__p.bb.GetSbyte(o + __p.bb_pos) : tflite.TensorType.FLOAT32; } }

  public static Offset<tflite.ArgMinOptions> CreateArgMinOptions(FlatBufferBuilder builder,
      tflite.TensorType output_type = tflite.TensorType.FLOAT32) {
    builder.StartTable(1);
    ArgMinOptions.AddOutputType(builder, output_type);
    return ArgMinOptions.EndArgMinOptions(builder);
  }

  public static void StartArgMinOptions(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddOutputType(FlatBufferBuilder builder, tflite.TensorType outputType) { builder.AddSbyte(0, (sbyte)outputType, 0); }
  public static Offset<tflite.ArgMinOptions> EndArgMinOptions(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<tflite.ArgMinOptions>(o);
  }
};


}
