// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct CallOnceOptions : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static CallOnceOptions GetRootAsCallOnceOptions(ByteBuffer _bb) { return GetRootAsCallOnceOptions(_bb, new CallOnceOptions()); }
  public static CallOnceOptions GetRootAsCallOnceOptions(ByteBuffer _bb, CallOnceOptions obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CallOnceOptions __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int InitSubgraphIndex { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<tflite.CallOnceOptions> CreateCallOnceOptions(FlatBufferBuilder builder,
      int init_subgraph_index = 0) {
    builder.StartTable(1);
    CallOnceOptions.AddInitSubgraphIndex(builder, init_subgraph_index);
    return CallOnceOptions.EndCallOnceOptions(builder);
  }

  public static void StartCallOnceOptions(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddInitSubgraphIndex(FlatBufferBuilder builder, int initSubgraphIndex) { builder.AddInt(0, initSubgraphIndex, 0); }
  public static Offset<tflite.CallOnceOptions> EndCallOnceOptions(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<tflite.CallOnceOptions>(o);
  }
};


}
