// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

public enum CombinerType : sbyte
{
  SUM = 0,
  MEAN = 1,
  SQRTN = 2,
};


}
