// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Conv3DOptions : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static Conv3DOptions GetRootAsConv3DOptions(ByteBuffer _bb) { return GetRootAsConv3DOptions(_bb, new Conv3DOptions()); }
  public static Conv3DOptions GetRootAsConv3DOptions(ByteBuffer _bb, Conv3DOptions obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Conv3DOptions __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public tflite.Padding Padding { get { int o = __p.__offset(4); return o != 0 ? (tflite.Padding)__p.bb.GetSbyte(o + __p.bb_pos) : tflite.Padding.SAME; } }
  public int StrideD { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int StrideW { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int StrideH { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public tflite.ActivationFunctionType FusedActivationFunction { get { int o = __p.__offset(12); return o != 0 ? (tflite.ActivationFunctionType)__p.bb.GetSbyte(o + __p.bb_pos) : tflite.ActivationFunctionType.NONE; } }
  public int DilationDFactor { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)1; } }
  public int DilationWFactor { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)1; } }
  public int DilationHFactor { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)1; } }

  public static Offset<tflite.Conv3DOptions> CreateConv3DOptions(FlatBufferBuilder builder,
      tflite.Padding padding = tflite.Padding.SAME,
      int stride_d = 0,
      int stride_w = 0,
      int stride_h = 0,
      tflite.ActivationFunctionType fused_activation_function = tflite.ActivationFunctionType.NONE,
      int dilation_d_factor = 1,
      int dilation_w_factor = 1,
      int dilation_h_factor = 1) {
    builder.StartTable(8);
    Conv3DOptions.AddDilationHFactor(builder, dilation_h_factor);
    Conv3DOptions.AddDilationWFactor(builder, dilation_w_factor);
    Conv3DOptions.AddDilationDFactor(builder, dilation_d_factor);
    Conv3DOptions.AddStrideH(builder, stride_h);
    Conv3DOptions.AddStrideW(builder, stride_w);
    Conv3DOptions.AddStrideD(builder, stride_d);
    Conv3DOptions.AddFusedActivationFunction(builder, fused_activation_function);
    Conv3DOptions.AddPadding(builder, padding);
    return Conv3DOptions.EndConv3DOptions(builder);
  }

  public static void StartConv3DOptions(FlatBufferBuilder builder) { builder.StartTable(8); }
  public static void AddPadding(FlatBufferBuilder builder, tflite.Padding padding) { builder.AddSbyte(0, (sbyte)padding, 0); }
  public static void AddStrideD(FlatBufferBuilder builder, int strideD) { builder.AddInt(1, strideD, 0); }
  public static void AddStrideW(FlatBufferBuilder builder, int strideW) { builder.AddInt(2, strideW, 0); }
  public static void AddStrideH(FlatBufferBuilder builder, int strideH) { builder.AddInt(3, strideH, 0); }
  public static void AddFusedActivationFunction(FlatBufferBuilder builder, tflite.ActivationFunctionType fusedActivationFunction) { builder.AddSbyte(4, (sbyte)fusedActivationFunction, 0); }
  public static void AddDilationDFactor(FlatBufferBuilder builder, int dilationDFactor) { builder.AddInt(5, dilationDFactor, 1); }
  public static void AddDilationWFactor(FlatBufferBuilder builder, int dilationWFactor) { builder.AddInt(6, dilationWFactor, 1); }
  public static void AddDilationHFactor(FlatBufferBuilder builder, int dilationHFactor) { builder.AddInt(7, dilationHFactor, 1); }
  public static Offset<tflite.Conv3DOptions> EndConv3DOptions(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<tflite.Conv3DOptions>(o);
  }
};


}
