// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

public enum CustomOptionsFormat : sbyte
{
  FLEXBUFFERS = 0,
};


}
