// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct CustomQuantization : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static CustomQuantization GetRootAsCustomQuantization(ByteBuffer _bb) { return GetRootAsCustomQuantization(_bb, new CustomQuantization()); }
  public static CustomQuantization GetRootAsCustomQuantization(ByteBuffer _bb, CustomQuantization obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CustomQuantization __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte Custom(int j) { int o = __p.__offset(4); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int CustomLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCustomBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetCustomBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetCustomArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<tflite.CustomQuantization> CreateCustomQuantization(FlatBufferBuilder builder,
      VectorOffset customOffset = default(VectorOffset)) {
    builder.StartTable(1);
    CustomQuantization.AddCustom(builder, customOffset);
    return CustomQuantization.EndCustomQuantization(builder);
  }

  public static void StartCustomQuantization(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddCustom(FlatBufferBuilder builder, VectorOffset customOffset) { builder.AddOffset(0, customOffset.Value, 0); }
  public static VectorOffset CreateCustomVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateCustomVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static void StartCustomVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<tflite.CustomQuantization> EndCustomQuantization(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<tflite.CustomQuantization>(o);
  }
};


}
