// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DensifyOptions : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DensifyOptions GetRootAsDensifyOptions(ByteBuffer _bb) { return GetRootAsDensifyOptions(_bb, new DensifyOptions()); }
  public static DensifyOptions GetRootAsDensifyOptions(ByteBuffer _bb, DensifyOptions obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DensifyOptions __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartDensifyOptions(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<tflite.DensifyOptions> EndDensifyOptions(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<tflite.DensifyOptions>(o);
  }
};


}
