// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DepthwiseConv2DOptions : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DepthwiseConv2DOptions GetRootAsDepthwiseConv2DOptions(ByteBuffer _bb) { return GetRootAsDepthwiseConv2DOptions(_bb, new DepthwiseConv2DOptions()); }
  public static DepthwiseConv2DOptions GetRootAsDepthwiseConv2DOptions(ByteBuffer _bb, DepthwiseConv2DOptions obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DepthwiseConv2DOptions __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public tflite.Padding Padding { get { int o = __p.__offset(4); return o != 0 ? (tflite.Padding)__p.bb.GetSbyte(o + __p.bb_pos) : tflite.Padding.SAME; } }
  public int StrideW { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int StrideH { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int DepthMultiplier { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public tflite.ActivationFunctionType FusedActivationFunction { get { int o = __p.__offset(12); return o != 0 ? (tflite.ActivationFunctionType)__p.bb.GetSbyte(o + __p.bb_pos) : tflite.ActivationFunctionType.NONE; } }
  public int DilationWFactor { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)1; } }
  public int DilationHFactor { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)1; } }

  public static Offset<tflite.DepthwiseConv2DOptions> CreateDepthwiseConv2DOptions(FlatBufferBuilder builder,
      tflite.Padding padding = tflite.Padding.SAME,
      int stride_w = 0,
      int stride_h = 0,
      int depth_multiplier = 0,
      tflite.ActivationFunctionType fused_activation_function = tflite.ActivationFunctionType.NONE,
      int dilation_w_factor = 1,
      int dilation_h_factor = 1) {
    builder.StartTable(7);
    DepthwiseConv2DOptions.AddDilationHFactor(builder, dilation_h_factor);
    DepthwiseConv2DOptions.AddDilationWFactor(builder, dilation_w_factor);
    DepthwiseConv2DOptions.AddDepthMultiplier(builder, depth_multiplier);
    DepthwiseConv2DOptions.AddStrideH(builder, stride_h);
    DepthwiseConv2DOptions.AddStrideW(builder, stride_w);
    DepthwiseConv2DOptions.AddFusedActivationFunction(builder, fused_activation_function);
    DepthwiseConv2DOptions.AddPadding(builder, padding);
    return DepthwiseConv2DOptions.EndDepthwiseConv2DOptions(builder);
  }

  public static void StartDepthwiseConv2DOptions(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddPadding(FlatBufferBuilder builder, tflite.Padding padding) { builder.AddSbyte(0, (sbyte)padding, 0); }
  public static void AddStrideW(FlatBufferBuilder builder, int strideW) { builder.AddInt(1, strideW, 0); }
  public static void AddStrideH(FlatBufferBuilder builder, int strideH) { builder.AddInt(2, strideH, 0); }
  public static void AddDepthMultiplier(FlatBufferBuilder builder, int depthMultiplier) { builder.AddInt(3, depthMultiplier, 0); }
  public static void AddFusedActivationFunction(FlatBufferBuilder builder, tflite.ActivationFunctionType fusedActivationFunction) { builder.AddSbyte(4, (sbyte)fusedActivationFunction, 0); }
  public static void AddDilationWFactor(FlatBufferBuilder builder, int dilationWFactor) { builder.AddInt(5, dilationWFactor, 1); }
  public static void AddDilationHFactor(FlatBufferBuilder builder, int dilationHFactor) { builder.AddInt(6, dilationHFactor, 1); }
  public static Offset<tflite.DepthwiseConv2DOptions> EndDepthwiseConv2DOptions(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<tflite.DepthwiseConv2DOptions>(o);
  }
};


}
