// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

public enum DimensionType : sbyte
{
  DENSE = 0,
  SPARSE_CSR = 1,
};


}
