// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct DivOptions : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static DivOptions GetRootAsDivOptions(ByteBuffer _bb) { return GetRootAsDivOptions(_bb, new DivOptions()); }
  public static DivOptions GetRootAsDivOptions(ByteBuffer _bb, DivOptions obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DivOptions __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public tflite.ActivationFunctionType FusedActivationFunction { get { int o = __p.__offset(4); return o != 0 ? (tflite.ActivationFunctionType)__p.bb.GetSbyte(o + __p.bb_pos) : tflite.ActivationFunctionType.NONE; } }

  public static Offset<tflite.DivOptions> CreateDivOptions(FlatBufferBuilder builder,
      tflite.ActivationFunctionType fused_activation_function = tflite.ActivationFunctionType.NONE) {
    builder.StartTable(1);
    DivOptions.AddFusedActivationFunction(builder, fused_activation_function);
    return DivOptions.EndDivOptions(builder);
  }

  public static void StartDivOptions(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddFusedActivationFunction(FlatBufferBuilder builder, tflite.ActivationFunctionType fusedActivationFunction) { builder.AddSbyte(0, (sbyte)fusedActivationFunction, 0); }
  public static Offset<tflite.DivOptions> EndDivOptions(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<tflite.DivOptions>(o);
  }
};


}
