// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

public enum FullyConnectedOptionsWeightsFormat : sbyte
{
  DEFAULT = 0,
  SHUFFLED4x16INT8 = 1,
};


}
