// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct GatherOptions : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static GatherOptions GetRootAsGatherOptions(ByteBuffer _bb) { return GetRootAsGatherOptions(_bb, new GatherOptions()); }
  public static GatherOptions GetRootAsGatherOptions(ByteBuffer _bb, GatherOptions obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GatherOptions __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Axis { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<tflite.GatherOptions> CreateGatherOptions(FlatBufferBuilder builder,
      int axis = 0) {
    builder.StartTable(1);
    GatherOptions.AddAxis(builder, axis);
    return GatherOptions.EndGatherOptions(builder);
  }

  public static void StartGatherOptions(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddAxis(FlatBufferBuilder builder, int axis) { builder.AddInt(0, axis, 0); }
  public static Offset<tflite.GatherOptions> EndGatherOptions(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<tflite.GatherOptions>(o);
  }
};


}
