// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct LSHProjectionOptions : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static LSHProjectionOptions GetRootAsLSHProjectionOptions(ByteBuffer _bb) { return GetRootAsLSHProjectionOptions(_bb, new LSHProjectionOptions()); }
  public static LSHProjectionOptions GetRootAsLSHProjectionOptions(ByteBuffer _bb, LSHProjectionOptions obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LSHProjectionOptions __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public tflite.LSHProjectionType Type { get { int o = __p.__offset(4); return o != 0 ? (tflite.LSHProjectionType)__p.bb.GetSbyte(o + __p.bb_pos) : tflite.LSHProjectionType.UNKNOWN; } }

  public static Offset<tflite.LSHProjectionOptions> CreateLSHProjectionOptions(FlatBufferBuilder builder,
      tflite.LSHProjectionType type = tflite.LSHProjectionType.UNKNOWN) {
    builder.StartTable(1);
    LSHProjectionOptions.AddType(builder, type);
    return LSHProjectionOptions.EndLSHProjectionOptions(builder);
  }

  public static void StartLSHProjectionOptions(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddType(FlatBufferBuilder builder, tflite.LSHProjectionType type) { builder.AddSbyte(0, (sbyte)type, 0); }
  public static Offset<tflite.LSHProjectionOptions> EndLSHProjectionOptions(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<tflite.LSHProjectionOptions>(o);
  }
};


}
