// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

public enum LSHProjectionType : sbyte
{
  UNKNOWN = 0,
  SPARSE = 1,
  DENSE = 2,
};


}
