// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

public enum LSTMKernelType : sbyte
{
  FULL = 0,
  BASIC = 1,
};


}
