// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

public enum MirrorPadMode : sbyte
{
  REFLECT = 0,
  SYMMETRIC = 1,
};


}
