// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct NonMaxSuppressionV5Options : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static NonMaxSuppressionV5Options GetRootAsNonMaxSuppressionV5Options(ByteBuffer _bb) { return GetRootAsNonMaxSuppressionV5Options(_bb, new NonMaxSuppressionV5Options()); }
  public static NonMaxSuppressionV5Options GetRootAsNonMaxSuppressionV5Options(ByteBuffer _bb, NonMaxSuppressionV5Options obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public NonMaxSuppressionV5Options __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartNonMaxSuppressionV5Options(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<tflite.NonMaxSuppressionV5Options> EndNonMaxSuppressionV5Options(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<tflite.NonMaxSuppressionV5Options>(o);
  }
};


}
