// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct NonMaxSuppressionV4Options : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static NonMaxSuppressionV4Options GetRootAsNonMaxSuppressionV4Options(ByteBuffer _bb) { return GetRootAsNonMaxSuppressionV4Options(_bb, new NonMaxSuppressionV4Options()); }
  public static NonMaxSuppressionV4Options GetRootAsNonMaxSuppressionV4Options(ByteBuffer _bb, NonMaxSuppressionV4Options obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public NonMaxSuppressionV4Options __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartNonMaxSuppressionV4Options(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<tflite.NonMaxSuppressionV4Options> EndNonMaxSuppressionV4Options(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<tflite.NonMaxSuppressionV4Options>(o);
  }
};


}
