// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Pool2DOptions : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static Pool2DOptions GetRootAsPool2DOptions(ByteBuffer _bb) { return GetRootAsPool2DOptions(_bb, new Pool2DOptions()); }
  public static Pool2DOptions GetRootAsPool2DOptions(ByteBuffer _bb, Pool2DOptions obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Pool2DOptions __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public tflite.Padding Padding { get { int o = __p.__offset(4); return o != 0 ? (tflite.Padding)__p.bb.GetSbyte(o + __p.bb_pos) : tflite.Padding.SAME; } }
  public int StrideW { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int StrideH { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int FilterWidth { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int FilterHeight { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public tflite.ActivationFunctionType FusedActivationFunction { get { int o = __p.__offset(14); return o != 0 ? (tflite.ActivationFunctionType)__p.bb.GetSbyte(o + __p.bb_pos) : tflite.ActivationFunctionType.NONE; } }

  public static Offset<tflite.Pool2DOptions> CreatePool2DOptions(FlatBufferBuilder builder,
      tflite.Padding padding = tflite.Padding.SAME,
      int stride_w = 0,
      int stride_h = 0,
      int filter_width = 0,
      int filter_height = 0,
      tflite.ActivationFunctionType fused_activation_function = tflite.ActivationFunctionType.NONE) {
    builder.StartTable(6);
    Pool2DOptions.AddFilterHeight(builder, filter_height);
    Pool2DOptions.AddFilterWidth(builder, filter_width);
    Pool2DOptions.AddStrideH(builder, stride_h);
    Pool2DOptions.AddStrideW(builder, stride_w);
    Pool2DOptions.AddFusedActivationFunction(builder, fused_activation_function);
    Pool2DOptions.AddPadding(builder, padding);
    return Pool2DOptions.EndPool2DOptions(builder);
  }

  public static void StartPool2DOptions(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddPadding(FlatBufferBuilder builder, tflite.Padding padding) { builder.AddSbyte(0, (sbyte)padding, 0); }
  public static void AddStrideW(FlatBufferBuilder builder, int strideW) { builder.AddInt(1, strideW, 0); }
  public static void AddStrideH(FlatBufferBuilder builder, int strideH) { builder.AddInt(2, strideH, 0); }
  public static void AddFilterWidth(FlatBufferBuilder builder, int filterWidth) { builder.AddInt(3, filterWidth, 0); }
  public static void AddFilterHeight(FlatBufferBuilder builder, int filterHeight) { builder.AddInt(4, filterHeight, 0); }
  public static void AddFusedActivationFunction(FlatBufferBuilder builder, tflite.ActivationFunctionType fusedActivationFunction) { builder.AddSbyte(5, (sbyte)fusedActivationFunction, 0); }
  public static Offset<tflite.Pool2DOptions> EndPool2DOptions(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<tflite.Pool2DOptions>(o);
  }
};


}
