// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

public enum QuantizationDetails : byte
{
  NONE = 0,
  CustomQuantization = 1,
};


}
