// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ReverseV2Options : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static ReverseV2Options GetRootAsReverseV2Options(ByteBuffer _bb) { return GetRootAsReverseV2Options(_bb, new ReverseV2Options()); }
  public static ReverseV2Options GetRootAsReverseV2Options(ByteBuffer _bb, ReverseV2Options obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ReverseV2Options __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartReverseV2Options(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<tflite.ReverseV2Options> EndReverseV2Options(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<tflite.ReverseV2Options>(o);
  }
};


}
