// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Rfft2dOptions : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static Rfft2dOptions GetRootAsRfft2dOptions(ByteBuffer _bb) { return GetRootAsRfft2dOptions(_bb, new Rfft2dOptions()); }
  public static Rfft2dOptions GetRootAsRfft2dOptions(ByteBuffer _bb, Rfft2dOptions obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Rfft2dOptions __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartRfft2dOptions(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<tflite.Rfft2dOptions> EndRfft2dOptions(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<tflite.Rfft2dOptions>(o);
  }
};


}
