// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct ShapeOptions : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static ShapeOptions GetRootAsShapeOptions(ByteBuffer _bb) { return GetRootAsShapeOptions(_bb, new ShapeOptions()); }
  public static ShapeOptions GetRootAsShapeOptions(ByteBuffer _bb, ShapeOptions obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ShapeOptions __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public tflite.TensorType OutType { get { int o = __p.__offset(4); return o != 0 ? (tflite.TensorType)__p.bb.GetSbyte(o + __p.bb_pos) : tflite.TensorType.FLOAT32; } }

  public static Offset<tflite.ShapeOptions> CreateShapeOptions(FlatBufferBuilder builder,
      tflite.TensorType out_type = tflite.TensorType.FLOAT32) {
    builder.StartTable(1);
    ShapeOptions.AddOutType(builder, out_type);
    return ShapeOptions.EndShapeOptions(builder);
  }

  public static void StartShapeOptions(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddOutType(FlatBufferBuilder builder, tflite.TensorType outType) { builder.AddSbyte(0, (sbyte)outType, 0); }
  public static Offset<tflite.ShapeOptions> EndShapeOptions(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<tflite.ShapeOptions>(o);
  }
};


}
