// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct TopKV2Options : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static TopKV2Options GetRootAsTopKV2Options(ByteBuffer _bb) { return GetRootAsTopKV2Options(_bb, new TopKV2Options()); }
  public static TopKV2Options GetRootAsTopKV2Options(ByteBuffer _bb, TopKV2Options obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TopKV2Options __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartTopKV2Options(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<tflite.TopKV2Options> EndTopKV2Options(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<tflite.TopKV2Options>(o);
  }
};


}
