// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct TransposeConvOptions : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static TransposeConvOptions GetRootAsTransposeConvOptions(ByteBuffer _bb) { return GetRootAsTransposeConvOptions(_bb, new TransposeConvOptions()); }
  public static TransposeConvOptions GetRootAsTransposeConvOptions(ByteBuffer _bb, TransposeConvOptions obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TransposeConvOptions __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public tflite.Padding Padding { get { int o = __p.__offset(4); return o != 0 ? (tflite.Padding)__p.bb.GetSbyte(o + __p.bb_pos) : tflite.Padding.SAME; } }
  public int StrideW { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int StrideH { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<tflite.TransposeConvOptions> CreateTransposeConvOptions(FlatBufferBuilder builder,
      tflite.Padding padding = tflite.Padding.SAME,
      int stride_w = 0,
      int stride_h = 0) {
    builder.StartTable(3);
    TransposeConvOptions.AddStrideH(builder, stride_h);
    TransposeConvOptions.AddStrideW(builder, stride_w);
    TransposeConvOptions.AddPadding(builder, padding);
    return TransposeConvOptions.EndTransposeConvOptions(builder);
  }

  public static void StartTransposeConvOptions(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddPadding(FlatBufferBuilder builder, tflite.Padding padding) { builder.AddSbyte(0, (sbyte)padding, 0); }
  public static void AddStrideW(FlatBufferBuilder builder, int strideW) { builder.AddInt(1, strideW, 0); }
  public static void AddStrideH(FlatBufferBuilder builder, int strideH) { builder.AddInt(2, strideH, 0); }
  public static Offset<tflite.TransposeConvOptions> EndTransposeConvOptions(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<tflite.TransposeConvOptions>(o);
  }
};


}
