// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct UnpackOptions : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static UnpackOptions GetRootAsUnpackOptions(ByteBuffer _bb) { return GetRootAsUnpackOptions(_bb, new UnpackOptions()); }
  public static UnpackOptions GetRootAsUnpackOptions(ByteBuffer _bb, UnpackOptions obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public UnpackOptions __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Num { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Axis { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<tflite.UnpackOptions> CreateUnpackOptions(FlatBufferBuilder builder,
      int num = 0,
      int axis = 0) {
    builder.StartTable(2);
    UnpackOptions.AddAxis(builder, axis);
    UnpackOptions.AddNum(builder, num);
    return UnpackOptions.EndUnpackOptions(builder);
  }

  public static void StartUnpackOptions(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddNum(FlatBufferBuilder builder, int num) { builder.AddInt(0, num, 0); }
  public static void AddAxis(FlatBufferBuilder builder, int axis) { builder.AddInt(1, axis, 0); }
  public static Offset<tflite.UnpackOptions> EndUnpackOptions(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<tflite.UnpackOptions>(o);
  }
};


}
