// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct WhereOptions : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static WhereOptions GetRootAsWhereOptions(ByteBuffer _bb) { return GetRootAsWhereOptions(_bb, new WhereOptions()); }
  public static WhereOptions GetRootAsWhereOptions(ByteBuffer _bb, WhereOptions obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public WhereOptions __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartWhereOptions(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<tflite.WhereOptions> EndWhereOptions(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<tflite.WhereOptions>(o);
  }
};


}
