// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace tflite
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct WhileOptions : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static WhileOptions GetRootAsWhileOptions(ByteBuffer _bb) { return GetRootAsWhileOptions(_bb, new WhileOptions()); }
  public static WhileOptions GetRootAsWhileOptions(ByteBuffer _bb, WhileOptions obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public WhileOptions __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int CondSubgraphIndex { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int BodySubgraphIndex { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<tflite.WhileOptions> CreateWhileOptions(FlatBufferBuilder builder,
      int cond_subgraph_index = 0,
      int body_subgraph_index = 0) {
    builder.StartTable(2);
    WhileOptions.AddBodySubgraphIndex(builder, body_subgraph_index);
    WhileOptions.AddCondSubgraphIndex(builder, cond_subgraph_index);
    return WhileOptions.EndWhileOptions(builder);
  }

  public static void StartWhileOptions(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddCondSubgraphIndex(FlatBufferBuilder builder, int condSubgraphIndex) { builder.AddInt(0, condSubgraphIndex, 0); }
  public static void AddBodySubgraphIndex(FlatBufferBuilder builder, int bodySubgraphIndex) { builder.AddInt(1, bodySubgraphIndex, 0); }
  public static Offset<tflite.WhileOptions> EndWhileOptions(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<tflite.WhileOptions>(o);
  }
};


}
